export {
  applications,
  blogPosts,
  caseStudies,
  ctaBanner,
  engineeringFeatures,
  faqs,
  featureBlocks,
  homepageStats,
  howItWorksSteps,
  homeHero,
  machineHotspots,
  materials,
  navigation,
  partnerLogos,
  productConfiguration,
  productShowcase,
  products,
  resources,
  specComparison,
  testimonials,
  trustBadges,
  videos,
  whyFeatures,
} from "@/lib/mock-data";
